# Generated by Django 4.1.3 on 2022-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='signature',
            field=models.CharField(default='firma', max_length=100),
        ),
    ]
